Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -14,16 +14,16 @@ pipeline {
   }
 
   options {
-    skipDefaultCheckout()
+    skipDefaultCheckout() // Explicit checkout
   }
 
   stages {
     stage('Checkout') {
       steps {
-        checkout([$class: 'GitSCM', 
-          branches: [[name: '*/main']], 
-          userRemoteConfigs: [[url: "https://github.com/${env.GIT_USER_NAME}/${env.GIT_REPO_NAME}.git"]]]
-        )
+        checkout([$class: 'GitSCM',
+          branches: [[name: '*/main']],
+          userRemoteConfigs: [[url: "https://github.com/${env.GIT_USER_NAME}/${env.GIT_REPO_NAME}.git"]]
+        ])
       }
     }
 
@@ -54,10 +54,10 @@ pipeline {
       }
       steps {
         script {
-          sh """
+          sh '''
             cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
             docker build -t ${DOCKER_IMAGE} .
-          """
+          '''
           def dockerImage = docker.image("${DOCKER_IMAGE}")
           docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
             dockerImage.push()
@@ -69,15 +69,23 @@ pipeline {
     stage('Update Deployment File') {
       steps {
         withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
-          dir('.') {
+          dir("${env.WORKSPACE}") {
             sh '''
+              echo "Current directory: $(pwd)"
+              ls -a
+
+              if [ ! -d ".git" ]; then
+                echo "ERROR: .git directory not found!"
+                exit 1
+              fi
+
               git config user.email "vamsikadiyam444@gmail.com"
               git config user.name "vamsikadiyam444"
 
               sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
 
-              git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-              git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+              git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml || true
+              git commit -m "Update deployment image to version ${BUILD_NUMBER}" || echo "No changes to commit"
               git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
             '''
           }
@@ -87,6 +95,9 @@ pipeline {
   }
 }
 
+          
+    
+           
           
  
 
